#!/bin/bash

# Define the log file
logfile="/var/log/secure"

# Print lines containing "sudo" between 0 and 6 hours
echo "Lines containing 'sudo' between midnight and 6 AM:"
awk '/ (00|01|02|03|04|05):[0-5][0-9]:[0-5][0-9]/ && /sudo/' "$logfile"

# Print lines containing "password" between 0 and 6 hours
echo "Lines containing 'password' between midnight and 6 AM:"
awk '/ (00|01|02|03|04|05):[0-5][0-9]:[0-5][0-9]/ && /password/' "$logfile"
