#!/bin/bash

# Define the log file
logfile="/var/log/secure"

# Count the number of lines between 0 and 6 hours
count=$(awk '/ (00|01|02|03|04|05):[0-5][0-9]:[0-5][0-9]/{count++} /Failed password/{print; password_count++} END{print "Total lines between 0 and 6 hours:", count, "Failed password attempts:", password_count}' "$logfile")

# Print the count
echo "$count"
